<?php

namespace SprykerEco\Shared\Optivo;

class OptivoConstants
{
    public const REQUEST_BASE_URL = 'OPTIVO:REQUEST_BASE_URL';
    public const REQUEST_TIMEOUT = 'OPTIVO:REQUEST_TIMEOUT';

    public const CLIENT_ID = 'OPTIVO:CLIENT_ID';

    public const ORDER_LIST_AUTHORIZATION_CODE = 'OPTIVO:ORDER_LIST_AUTHORIZATION_CODE';
    public const CUSTOMER_LIST_AUTHORIZATION_CODE = 'OPTIVO:CUSTOMER_LIST_AUTHORIZATION_CODE';

    public const CUSTOMER_REGISTRATION_MAILING_ID = 'OPTIVO:EVENT_CUSTOMER_REGISTRATION';
    public const CUSTOMER_RESET_PASSWORD_MAILING_ID = 'OPTIVO:EVENT_CUSTOMER_RESET_PASSWORD';
    public const ORDER_NEW_MAILING_ID = 'OPTIVO:EVENT_ORDER_NEW';
    public const ORDER_SHIPPING_CONFIRMATION_MAILING_ID = 'OPTIVO:EVENT_ORDER_SHIPPING_CONFIRMATION';
    public const ORDER_CANCELLED_MAILING_ID = 'OPTIVO:EVENT_ORDER_CANCELLED';
    public const ORDER_PAYMENT_IS_NOT_RECEIVED_MAILING_ID = 'OPTIVO:EVENT_ORDER_PAYMENT_IS_NOT_RECEIVED';
}
