<?php

namespace SprykerEco\Shared\Optivo;

class OptivoConstants
{
    const REQUEST_BASE_URL = 'OPTIVO:REQUEST_BASE_URL';
    const REQUEST_TIMEOUT = 'OPTIVO:REQUEST_TIMEOUT';
    const TOKEN_OPERATION_SEND_TRANSACTION_EMAIL = 'OPTIVO:TOKEN_OPERATION_SEND_TRANSACTION_EMAIL';
    const TOKEN_OPERATION_SUBSCRIBE = 'OPTIVO:TOKEN_OPERATION_SUBSCRIBE';
    const TOKEN_OPERATION_UNSUBSCRIBE = 'OPTIVO:TOKEN_OPERATION_UNSUBSCRIBE';
}
